project_id = "ttzakubulphvibneblpm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.canvas-course-info]
verify_jwt = false

[functions.canvas-pages-list]
verify_jwt = false

[functions.canvas-page-create]
verify_jwt = false

[functions.canvas-page-update]
verify_jwt = false

[functions.canvas-image-upload]
verify_jwt = false

[functions.canvas-page-screenshot]
verify_jwt = false